"""Build local RAG and matching artifacts from a VC investor record.

The input is the canonical ``*-record.json`` generated by the VC research
workflow. The output is a small set of JSON/JSONL files that can be inspected
locally or loaded into PostgreSQL/Aurora later.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


CONFIDENCE_MAP = {
    "high": "high",
    "medium-high": "medium_high",
    "medium_high": "medium_high",
    "medium": "medium",
    "low": "low",
    "gap": "gap",
    "Gap": "gap",
    "unknown": "unknown",
    None: "unknown",
}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows)
    path.write_text(text, encoding="utf-8")


def normalize_confidence(value: Any) -> str:
    return CONFIDENCE_MAP.get(value, CONFIDENCE_MAP.get(str(value).strip(), "unknown"))


def investor_id(record: dict[str, Any]) -> str:
    investor = record.get("investor", {})
    value = investor.get("investor_id")
    if not value:
        raise ValueError("record.investor.investor_id is required")
    return str(value)


def investor_name(record: dict[str, Any]) -> str:
    return str(record.get("investor", {}).get("investor_name") or investor_id(record))


def field_map(record: dict[str, Any]) -> dict[str, dict[str, Any]]:
    fields = {}
    for item in record.get("investor_fields", []):
        key = item.get("field")
        if key:
            fields[str(key)] = item
    return fields


def stable_id(*parts: Any) -> str:
    raw = ":".join(str(part) for part in parts if part is not None)
    digest = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:12]
    clean = raw.lower().replace(" ", "_").replace("/", "_")
    clean = "".join(ch for ch in clean if ch.isalnum() or ch in "_:-")
    return f"{clean}:{digest}"


def short_json(value: Any, max_len: int = 420) -> str:
    text = json.dumps(value, ensure_ascii=False, sort_keys=True)
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def money_text(amount: dict[str, Any] | None) -> str:
    if not isinstance(amount, dict) or amount.get("value") is None:
        return "Gap"
    value = amount.get("value")
    currency = amount.get("currency") or ""
    unit = amount.get("unit") or ""
    return " ".join(str(part) for part in [currency, value, unit] if part).strip()


def collect_source_urls_from_deal(deal: dict[str, Any]) -> list[str]:
    urls = []
    for source in deal.get("deal_sources", []) or []:
        url = source.get("url")
        if url:
            urls.append(url)
    return urls


def chunk(
    *,
    inv_id: str,
    entity_type: str,
    entity_id: str,
    section_key: str,
    text: str,
    fact_kind: str,
    confidence: str,
    review_needed: bool,
    source_urls: list[str] | None = None,
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "local_chunk_id": stable_id(inv_id, entity_type, entity_id, section_key, text[:80]),
        "investor_id": inv_id,
        "entity_type": entity_type,
        "entity_id": entity_id,
        "section_key": section_key,
        "chunk_text": text,
        "fact_kind": fact_kind,
        "confidence": normalize_confidence(confidence),
        "review_needed": bool(review_needed),
        "rag_allowed": True,
        "source_urls": source_urls or [],
        "metadata": metadata or {},
    }


def build_matching_profile(record: dict[str, Any]) -> dict[str, Any]:
    inv = record.get("investor", {})
    inv_id = investor_id(record)
    fields = field_map(record)
    deals = [deal for deal in record.get("deals", []) if deal.get("in_window", True)]

    def field_value(key: str, default: Any = None) -> Any:
        return fields.get(key, {}).get("value", default)

    def field_conf(key: str) -> str:
        return normalize_confidence(fields.get(key, {}).get("confidence"))

    cheque = field_value("cheque_size", {}) or {}
    business_model = field_value("business_model_tendency", {}) or {}
    contact_path = field_value("contact_path", {}) or {}
    deals_last_24mo = field_value("deals_last_24mo", {}) or {}

    first_cheque_stages = sorted(
        {
            str(deal.get("round_stage"))
            for deal in deals
            if deal.get("is_new_investment_for_investor") and deal.get("round_stage")
        }
    )
    supported_business_models = sorted(
        {
            str(deal.get("business_model_orientation"))
            for deal in deals
            if deal.get("business_model_orientation") and deal.get("business_model_orientation") != "Gap"
        }
    )
    review_needed_fields = sorted(
        {
            item.get("field")
            for item in record.get("investor_fields", [])
            if normalize_confidence(item.get("confidence")) in {"medium", "low", "gap", "unknown"}
        }
        | {
            task.get("field")
            for task in record.get("review_tasks", [])
            if task.get("status", "open") in {"open", "draft"}
        }
    )

    return {
        "investor_id": inv_id,
        "investor_name": investor_name(record),
        "local_au_anz_fund": bool(field_value("local_au_anz_fund", False)),
        "au_anz_relevance": field_value("anz_relevance"),
        "au_anz_relevance_confidence": field_conf("anz_relevance"),
        "supported_stages": inv.get("stages_actual", []),
        "first_cheque_stages": first_cheque_stages,
        "supported_sectors": inv.get("sectors_actual", []),
        "supported_business_models": supported_business_models,
        "business_model_distribution": business_model.get("distribution", {}),
        "cheque_size": {
            "min": cheque.get("min"),
            "max": cheque.get("max"),
            "basis": cheque.get("basis"),
            "hard_filter_safe": bool(cheque.get("hard_filter_safe", False)),
            "confidence": field_conf("cheque_size"),
        },
        "lead_behavior": inv.get("leads_rounds"),
        "recent_activity": {
            "value": deals_last_24mo,
            "confidence": field_conf("deals_last_24mo"),
        },
        "contact_path": contact_path,
        "warm_intro_required": (
            None
            if not isinstance(contact_path, dict)
            else not bool(contact_path.get("no_intro_required", False))
        ),
        "review_needed_fields": [field for field in review_needed_fields if field],
        "field_confidences": {
            key: normalize_confidence(value.get("confidence")) for key, value in fields.items()
        },
    }


def build_rag_chunks(record: dict[str, Any]) -> list[dict[str, Any]]:
    inv_id = investor_id(record)
    inv_name = investor_name(record)
    chunks: list[dict[str, Any]] = []

    for item in record.get("rag_chunks", []) or []:
        body = item.get("body")
        if not body:
            continue
        chunks.append(
            chunk(
                inv_id=inv_id,
                entity_type="investor",
                entity_id=f"fund_{inv_id}",
                section_key=str(item.get("section_key") or "record_chunk"),
                text=str(body),
                fact_kind=str(item.get("fact_or_inference") or "mixed"),
                confidence=item.get("confidence"),
                review_needed=normalize_confidence(item.get("confidence")) in {"medium", "low", "gap"},
                metadata={
                    "region_scope": item.get("region_scope"),
                    "source": "record.rag_chunks",
                },
            )
        )

    for item in record.get("investor_fields", []) or []:
        key = item.get("field")
        if not key:
            continue
        confidence = normalize_confidence(item.get("confidence"))
        value = item.get("value")
        note = item.get("note")
        text = (
            f"{inv_name} matching field '{key}' has value {short_json(value)}. "
            f"Confidence: {confidence}."
        )
        if note:
            text += f" Note: {note}"
        chunks.append(
            chunk(
                inv_id=inv_id,
                entity_type="field",
                entity_id=f"fund_{inv_id}",
                section_key=f"matching_field:{key}",
                text=text,
                fact_kind="mixed",
                confidence=confidence,
                review_needed=confidence in {"medium", "low", "gap", "unknown"},
                metadata={"field_key": key, "source": "record.investor_fields"},
            )
        )

    for deal in record.get("deals", []) or []:
        deal_id = str(deal.get("deal_id") or stable_id(inv_id, deal.get("company")))
        amount = money_text(deal.get("round_amount"))
        confidence = normalize_confidence(deal.get("deal_confidence"))
        text = (
            f"{inv_name} deal evidence: {deal.get('company')} announced "
            f"{deal.get('round_stage')} on {deal.get('announced_date')} "
            f"for {amount}. Role: {deal.get('role')}. "
            f"ANZ company relevance: {deal.get('company_anz_relevance')}; "
            f"investor mandate fit: {deal.get('investor_mandate_fit')} "
            f"({deal.get('investor_mandate_fit_basis')}). "
            f"Business model: {deal.get('business_model_orientation')} - "
            f"{deal.get('business_model_detail')}. "
            f"Verification status: {deal.get('verification_status')}."
        )
        if deal.get("notes"):
            text += f" Notes: {deal.get('notes')}"
        chunks.append(
            chunk(
                inv_id=inv_id,
                entity_type="deal",
                entity_id=deal_id,
                section_key="deal_evidence",
                text=text,
                fact_kind="fact",
                confidence=confidence,
                review_needed=bool(deal.get("missing_sources")) or confidence in {"medium", "low", "gap"},
                source_urls=collect_source_urls_from_deal(deal),
                metadata={
                    "company": deal.get("company"),
                    "round_stage": deal.get("round_stage"),
                    "business_model_orientation": deal.get("business_model_orientation"),
                    "company_anz_relevance": deal.get("company_anz_relevance"),
                    "investor_mandate_fit": deal.get("investor_mandate_fit"),
                    "verification_status": deal.get("verification_status"),
                    "source": "record.deals",
                },
            )
        )

    for route in record.get("partner_routing_hypotheses", []) or []:
        confidence = normalize_confidence(route.get("confidence"))
        sector = route.get("sector") or route.get("sector_or_use_case") or "routing"
        who = ", ".join(route.get("who", []) or route.get("suggested_partner_names", []) or [])
        text = (
            f"{inv_name} partner routing hypothesis for {sector}: {who}. "
            f"Evidence basis: {route.get('evidence_basis')}. "
            f"Confidence: {confidence}; reviewer needed: {route.get('reviewer_needed')}."
        )
        chunks.append(
            chunk(
                inv_id=inv_id,
                entity_type="routing",
                entity_id=f"fund_{inv_id}_partner_routing",
                section_key="partner_routing",
                text=text,
                fact_kind="inference",
                confidence=confidence,
                review_needed=bool(route.get("reviewer_needed", True)),
                metadata={"sector": sector, "source": "record.partner_routing_hypotheses"},
            )
        )

    for task in record.get("review_tasks", []) or []:
        text = (
            f"{inv_name} review task for {task.get('entity_type')} "
            f"{task.get('entity_id')} field {task.get('field')}: "
            f"{task.get('reason')} Suggested action: {task.get('suggested_action')}."
        )
        chunks.append(
            chunk(
                inv_id=inv_id,
                entity_type=str(task.get("entity_type") or "review_task"),
                entity_id=str(task.get("entity_id") or f"fund_{inv_id}"),
                section_key="review_gap",
                text=text,
                fact_kind="inference",
                confidence="low",
                review_needed=True,
                metadata={
                    "field_key": task.get("field"),
                    "priority": task.get("priority"),
                    "status": task.get("status"),
                    "source": "record.review_tasks",
                },
            )
        )

    return chunks


def build_sources(record: dict[str, Any]) -> list[dict[str, Any]]:
    inv_id = investor_id(record)
    sources: list[dict[str, Any]] = []

    for url in record.get("sources_primary", []) or []:
        sources.append(
            {
                "investor_id": inv_id,
                "entity_type": "investor",
                "entity_id": f"fund_{inv_id}",
                "url": url,
                "source_type": "official_fund_page",
                "source_role": "primary",
                "publisher": None,
                "source_strength": "strong",
            }
        )

    for deal in record.get("deals", []) or []:
        for source in deal.get("deal_sources", []) or []:
            row = dict(source)
            row.update(
                {
                    "investor_id": inv_id,
                    "entity_type": "deal",
                    "entity_id": deal.get("deal_id"),
                }
            )
            sources.append(row)

    for edge in record.get("co_investment_edges", []) or []:
        if edge.get("evidence_url"):
            sources.append(
                {
                    "investor_id": inv_id,
                    "entity_type": "co_investment_edge",
                    "entity_id": edge.get("related_deal_id") or edge.get("related_company"),
                    "url": edge.get("evidence_url"),
                    "source_type": edge.get("source_type", "other"),
                    "source_role": "context",
                    "publisher": None,
                    "source_strength": "medium",
                }
            )

    deduped = {}
    for source in sources:
        key = (source.get("entity_type"), source.get("entity_id"), source.get("url"))
        if key not in deduped:
            deduped[key] = source
    return list(deduped.values())


def build_review_tasks(record: dict[str, Any]) -> list[dict[str, Any]]:
    inv_id = investor_id(record)
    rows = []
    for task in record.get("review_tasks", []) or []:
        row = dict(task)
        row["investor_id"] = inv_id
        rows.append(row)
    return rows


def build_manifest(record_path: Path, output_dir: Path, record: dict[str, Any]) -> dict[str, Any]:
    raw = record_path.read_bytes()
    return {
        "investor_id": investor_id(record),
        "investor_name": investor_name(record),
        "source_record_path": str(record_path),
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "output_dir": str(output_dir),
        "files": {
            "matching_profile": "matching_profile.json",
            "rag_chunks": "rag_chunks.jsonl",
            "sources": "sources.jsonl",
            "review_tasks": "review_tasks.jsonl",
            "raw_record_copy": "record.json",
        },
    }


def build_artifacts(record_path: Path, out_dir: Path) -> dict[str, Any]:
    record = load_json(record_path)
    inv_id = investor_id(record)
    target_dir = out_dir / inv_id

    matching_profile = build_matching_profile(record)
    rag_chunks = build_rag_chunks(record)
    sources = build_sources(record)
    review_tasks = build_review_tasks(record)
    manifest = build_manifest(record_path, target_dir, record)

    write_json(target_dir / "record.json", record)
    write_json(target_dir / "matching_profile.json", matching_profile)
    write_jsonl(target_dir / "rag_chunks.jsonl", rag_chunks)
    write_jsonl(target_dir / "sources.jsonl", sources)
    write_jsonl(target_dir / "review_tasks.jsonl", review_tasks)
    write_json(target_dir / "manifest.json", manifest)

    return {
        "investor_id": inv_id,
        "output_dir": str(target_dir),
        "matching_fields": len(matching_profile),
        "rag_chunks": len(rag_chunks),
        "sources": len(sources),
        "review_tasks": len(review_tasks),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Build VC RAG artifacts from a record JSON")
    parser.add_argument("--record", required=True, type=Path, help="Path to <investor_id>-record.json")
    parser.add_argument("--out", default=Path("outputs"), type=Path, help="Output directory")
    args = parser.parse_args()

    result = build_artifacts(args.record, args.out)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
